title: Dyno Custom Commands
repotitle: Dyno Custom Commands
author: The DCC Team
authorurl: https://dynocc.tk/staff
url: https://dynocc.tk
remote_theme: advaith1/architect
head_code: <script>var _bftn_options = { theme: 'glitch' };</script><script src="https://widget.battleforthenet.com/widget.js" async></script>
